spring:
  # 配置数据源信息
  datasource:
    url: jdbc:mysql://localhost:3306/powercompetition?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  configuration:
    #配置Mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis-plus表的前缀
      #table-prefix: t_
      #配置mybatis-plus主键生成策略
      id-type: auto